FROM node:20.18.0@sha256:a5e0ed56f2c20b9689e0f7dd498cac7e08d2a3a283e92d9304e7b9b83e3c6ff3

WORKDIR /app

ARG VITE_BACKEND_APP_API_URL
ENV VITE_BACKEND_APP_API_URL $VITE_BACKEND_APP_API_URL
COPY package.json .

RUN npm install --legacy-peer-deps

COPY . .

EXPOSE 11080

CMD [ "npm", "run", "dev" ]
