services:
  gaganyatri_backend:
    container_name: gaganyatri_backend 
    hostname: gaganyatri_backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:10000"
    privileged: true
    tty: true
    env_file:
      - ./.env.dev
    volumes:
      - static:/static
      - ./backend/:/app
    ports: 
      - '10000:10000'
    networks:
      - gaganyatri_net
    extra_hosts:
      host.docker.internal: host-gateway
  gaganyatri_frontend:
    container_name: gaganyatri_frontend 
    hostname: gaganyatri_frontend
    build:
      context: frontend 
      dockerfile: Dockerfile.dev
    ports: 
      - '11080:11080'  
    depends_on:
      - gaganyatri_backend
    networks:
      - gaganyatri_net
    env_file:
      - ./.env.dev
    extra_hosts:
      host.docker.internal: host-gateway
networks:
  gaganyatri_net:
    driver: bridge
volumes:
  static:
