# Generated by Django 5.1.3 on 2024-11-24 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('iso_code', models.CharField(max_length=3, unique=True)),
                ('gdp', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('effective_tax_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('part_of_pillar2', models.BooleanField(default=False)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
