# Generated by Django 5.1.3 on 2024-11-24 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='effective_tax_rate',
        ),
        migrations.RemoveField(
            model_name='country',
            name='gdp',
        ),
        migrations.AddField(
            model_name='country',
            name='local_top_up_tax',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='country',
            name='pillar2_implemented',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='country',
            name='iso_code',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='country',
            name='latitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='country',
            name='longitude',
            field=models.FloatField(),
        ),
    ]
