# Generated by Django 5.1.3 on 2024-11-24 15:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_countrydata_questionnaire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countrydata',
            name='balance_sheet',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='countrydata',
            name='company_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='countrydata',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.country'),
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('balance_sheet', models.JSONField()),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='companies', to='dashboard.country')),
            ],
        ),
    ]
