# Generated by Django 5.1.1 on 2024-09-26 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_mymodel_prompt'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyModel',
        ),
    ]
