services:
  vllm:
    image: vllm-audio
    runtime: nvidia
    environment:
      - TRANSFORMERS_OFFLINE=1
      - HF_DATASET_OFFLINE=1
    volumes:
      - ~/.cache/huggingface:/root/.cache/huggingface
    ports:
      - 8000:8000
    command: --model fixie-ai/ultravox-v0_3-llama-3_2-1b --trust-remote-code --dtype half
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['0']
              capabilities: [gpu]
