# Generated by Django 5.1.1 on 2024-11-24 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TaxTechApp',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('appointment_day', models.DateField()),
                ('company_name', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=255)),
                ('observations', models.TextField()),
            ],
        ),
    ]
