# Generated by Django 5.1.1 on 2024-11-25 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxtech', '0002_auto_20241124_1235'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('currency', models.CharField(max_length=10)),
                ('ebt', models.IntegerField()),
                ('taxes', models.IntegerField()),
                ('revenues', models.IntegerField()),
                ('wages', models.IntegerField()),
                ('fixed_assets', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TaxData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=255)),
                ('currency', models.CharField(max_length=10)),
                ('ebt', models.IntegerField()),
                ('taxes', models.IntegerField()),
                ('quote', models.FloatField()),
                ('check_data', models.CharField(max_length=255)),
                ('pot_mehrsteuer', models.IntegerField()),
                ('de_minimis', models.CharField(max_length=10)),
                ('five_percent_check', models.IntegerField()),
                ('revenues', models.IntegerField(blank=True, null=True)),
                ('salaries', models.IntegerField()),
                ('net_loss', models.IntegerField()),
            ],
        ),
    ]
